version: "3.7"
services:
  #  pdf:
  #    ports:
  #      - "8080:8080"
  #    image: pdfdemo:latest

  vault:
    ports:
      - "8200:8200"
    image: hashicorp/vault:latest
    environment:
      - VAULT_DEV_ROOT_TOKEN_ID=dev-only-token
      - SKIP_SETCAP=true
    volumes:
      - /vault/file
      - /vault/logs
    cap_add:
      - IPC_LOCK
    restart: no
    runtime: runc

  prometheus:
    image: bitnami/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml

  loki:
    image: grafana/loki:latest
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    restart: unless-stopped
    volumes:
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources