services:
  pdf:
    ports:
      - "8080:8080"
    image: pdfdemo:latest
  vault:
    ports:
      - "8200:8200"
    image: vault:1.13.3
    environment:
      - VAULT_DEV_ROOT_TOKEN_ID=dev-only-token
      - SKIP_SETCAP=true
    volumes:
      - /vault/file
      - /vault/logs
    cap_add:
      - IPC_LOCK
    restart: no
    runtime: runc